### ISSUE TITLE
Release with semantic-release

### ISSUE THREAD

**Issue by andresmoschini** [MakingSense/doppler-feature-toggle-js#19]

**Comment by andresmoschini** [comment]
Problem:

![imagen](https://user-images.githubusercontent.com/1157864/44910887-33c33500-acfb-11e8-8908-923badefb3d4.png)

Solution:

![imagen](https://user-images.githubusercontent.com/1157864/44910766-d7601580-acfa-11e8-8479-72656b204055.png)

**Comment by andresmoschini** [comment]
Problem:

![imagen](https://user-images.githubusercontent.com/1157864/44910945-679e5a80-acfb-11e8-9f99-bf67a0b7c75c.png)

Reason: 

Semantic-release generates the file `.npmrc`

![imagen](https://user-images.githubusercontent.com/1157864/44911006-a207f780-acfb-11e8-8d08-fa5102064879.png)

Solutions

* Clean working dir on build?
* Delete the file before build?
* Delete the file after build?

**Comment by andresmoschini** [comment]
Problem:

NPM Upload is not working

```

root@docker:/var/lib/jenkins/workspace/doppler-feature-toggle-js/releases# ./build-n-publish.sh
yarn install v1.6.0
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 1.42s.
yarn run v1.6.0
$ yarn run prettier-check && yarn run lint && yarn run test --coverage --no-cache
$ prettier-check "{src,test}/**/*.ts"
All files using prettier code style.
$ tslint -t codeFrame 'src/**/*.ts' 'test/**/*.ts'
Warning: The 'no-boolean-literal-compare' rule requires type information.
$ jest --coverage --no-cache
PASS test/refFeatureToggleClient.test.ts
  RefFeatureToggleClient
    ✓ should return default value when featureName does not exist (7ms)
    ✓ should return default value when differentiator does not exist (1ms)
    ✓ should return default value when differentiator is related to another feature (1ms)
    ✓ should return defined value when rule matches (1ms)
    ✓ should accept rules updates (1ms)

---------------------------|----------|----------|----------|----------|-------------------|
File                       |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
---------------------------|----------|----------|----------|----------|-------------------|
All files                  |      100 |      100 |      100 |      100 |                   |
 refFeatureToggleClient.ts |      100 |      100 |      100 |      100 |                   |
---------------------------|----------|----------|----------|----------|-------------------|
Test Suites: 1 passed, 1 total
Tests:       5 passed, 5 total
Snapshots:   0 total
Time:        3.012s
Ran all test suites.
Done in 7.76s.
yarn run v1.6.0
$ rimraf dist
$ tsc --module commonjs && rollup -c rollup.config.ts && typedoc --out docs --target es6 --theme minimal --mode file src

src/doppler-feature-toggle.ts → dist/doppler-feature-toggle.umd.js, dist/doppler-feature-toggle.es5.js, dist/doppler-feature-toggle.client.js...
created dist/doppler-feature-toggle.umd.js, dist/doppler-feature-toggle.es5.js, dist/doppler-feature-toggle.client.js in 3.2s

Using TypeScript 2.7.2 from /work/node_modules/typedoc/node_modules/typescript/lib


Documentation generated at /work/docs

Done in 19.11s.
yarn run v1.6.0
$ /work/node_modules/.bin/semantic-release --no-ci
[23:20:48] [semantic-release] › ℹ  Running semantic-release version 15.9.9
[23:20:48] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[23:20:49] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[23:20:49] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[23:20:49] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[23:20:49] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[23:20:49] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[23:20:49] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[23:20:49] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[23:20:49] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[23:20:49] [semantic-release] › ✔  Run automated release from branch master
[23:20:49] [semantic-release] › ✔  Allowed to push to the Git repository
[23:20:49] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
[23:20:49] [semantic-release] [@semantic-release/npm] › ℹ  Verify authentication for registry https://registry.npmjs.org/
[23:20:49] [semantic-release] [@semantic-release/npm] › ℹ  Wrote NPM_TOKEN to /work/.npmrc
[23:20:50] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/npm"
[23:20:50] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/github"
[23:20:50] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication
[23:20:51] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/github"
[23:20:51] [semantic-release] › ℹ  Found git tag v1.0.0 associated with version 1.0.0
[23:20:51] [semantic-release] › ℹ  Found 21 commits since last release
[23:20:51] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[23:20:51] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Merge pull request #21 from andresmoschini/very-basic-implementation

Very basic implementation
[23:20:51] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[23:20:51] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: build(bundle): Fix entry point
[23:20:51] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[23:20:51] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Revert "test(dummy): add dummy code and tests"

This reverts commit 7aebe0631ada2f9a4ae8710f139bf61eb89dac0b.
[23:20:51] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[23:20:51] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: feat: Add very simple feature toggle client
[23:20:51] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is minor
[23:20:51] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Merge pull request #20 from andresmoschini/semantic-release

Add Semantic Release
[23:20:51] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[23:20:51] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: build(docker): add new script to allow publish using docker
[23:20:51] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[23:20:51] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: build(semantic-release): add Semantic Release
[23:20:51] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[23:20:51] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: build(docker): use `node:8` Docker image in place of `node:6-alpine`
[23:20:51] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[23:20:51] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: build(style): verify code format format with prettier-check

solves #15
[23:20:51] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[23:20:51] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: build(style): allow run Prettier manually

solves #15
[23:20:51] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[23:20:51] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: build(lint): adapt lint rules to my personal preferences

Override trailing-comma Airbnb TSlint configuration to avoid trailing comma and disallow usage of object literal shorthand.

I would prefer something like "consistent-as-needed" ESLint configuration, but it is not available for TSLint.

solves #16
[23:20:51] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[23:20:51] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: build(lint): add TSLint support

Allow linting alone and as part of test:prod process. Rules are based on Airbnb standards.

solves #16
[23:20:51] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[23:20:51] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: build(docs): Generate docs during build using Typedoc

Generates HTML documentation based on type metadata.

solves #17
[23:20:51] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[23:20:51] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: build(docker): add bash script for building using Docker Node container

I have ran this to apply executable permissions in Windows:

```
git update-index --chmod=+x foo.sh
```
[23:20:51] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[23:20:51] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: ci(travis): add .travis.yml
[23:20:51] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[23:20:51] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: build(dist): add new bundle output ready for browsers
[23:20:51] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[23:20:51] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: build(dist): allow build ES5 and UMD bundles with Rollup
[23:20:51] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[23:20:51] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: build(test): fix issue in Jest execution

```
 SecurityError: localStorage is not available for opaque origins

      at Window.get localStorage [as localStorage] (node_modules/jsdom/lib/jsdom/browser/Window.js:257:15)
          at Array.forEach (<anonymous>)
```

See more details in [HenrikHarmer's comment in jsdom issue #2304](https://github.com/jsdom/jsdom/issues/2304#issuecomment-408386234)
[23:20:51] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[23:20:51] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: build(test): allow running tests using Jest
[23:20:51] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[23:20:51] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: test(dummy): add dummy code and tests
[23:20:51] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[23:20:51] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: docs(readme): re-organize README and write about my decisions

The new organization has two main sections: Usage and Development. By the moment Usage section is empty because there is not any useful to be used.

In Development section there are information about my decisions related to technologies or how to used them, references and there will be instructions about scripts, tools or how to collaborate.
[23:20:51] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[23:20:51] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 21 commits complete: minor release
[23:20:51] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[23:20:51] [semantic-release] › ℹ  The next release version is 1.1.0
[23:20:51] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[23:20:51] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[23:20:51] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/npm"
[23:20:51] [semantic-release] [@semantic-release/npm] › ℹ  Wrote version 1.1.0 to /work/package.json
[23:20:51] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/npm"
[23:20:53] [semantic-release] › ✔  Created tag v1.1.0
[23:20:53] [semantic-release] › ℹ  Start step "publish" of plugin "@semantic-release/npm"
[23:20:54] [semantic-release] [@semantic-release/npm] › ℹ  Publishing version 1.1.0 to npm registry
npm notice
npm notice package: doppler-feature-toggle@1.1.0
npm notice === Tarball Contents ===
npm notice 2.4kB package.json
npm notice 1.1kB LICENSE
npm notice 4.0kB README.md
npm notice 5.0kB dist/doppler-feature-toggle.client.js
npm notice 1.9kB dist/doppler-feature-toggle.client.js.map
npm notice 4.6kB dist/doppler-feature-toggle.es5.js
npm notice 1.9kB dist/doppler-feature-toggle.es5.js.map
npm notice 5.3kB dist/doppler-feature-toggle.umd.js
npm notice 1.9kB dist/doppler-feature-toggle.umd.js.map
npm notice 393B  dist/lib/doppler-feature-toggle.js
npm notice 212B  dist/lib/doppler-feature-toggle.js.map
npm notice 124B  dist/lib/featureToggleClient.js
npm notice 133B  dist/lib/featureToggleClient.js.map
npm notice 123B  dist/lib/featureToggleRules.js
npm notice 131B  dist/lib/featureToggleRules.js.map
npm notice 3.8kB dist/lib/refFeatureToggleClient.js
npm notice 739B  dist/lib/refFeatureToggleClient.js.map
npm notice 68B   dist/types/doppler-feature-toggle.d.ts
npm notice 318B  dist/types/featureToggleClient.d.ts
npm notice 238B  dist/types/featureToggleRules.d.ts
npm notice 594B  dist/types/refFeatureToggleClient.d.ts
npm notice === Tarball Details ===
npm notice name:          doppler-feature-toggle
npm notice version:       1.1.0
npm notice package size:  7.5 kB
npm notice unpacked size: 34.9 kB
npm notice shasum:        57fba0d4f2a7b54ce2e7737f87ebf41f58f9bb01
npm notice integrity:     sha512-UnszL3HlpL/ma[...]herx6eOPPJudA==
npm notice total files:   21
npm notice
npm ERR! publish Failed PUT 403
npm ERR! code E403
npm ERR! You do not have permission to publish "doppler-feature-toggle". Are you logged in as the correct user? : doppler-feature-toggle

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-30T23_20_55_679Z-debug.log
[23:20:55] [semantic-release] › ✖  Failed step "publish" of plugin "@semantic-release/npm"
[23:20:55] [semantic-release] › ✖  An error occurred while running semantic-release: { Error: Command failed: npm publish /work --registry https://registry.npmjs.org/
npm notice
npm notice package: doppler-feature-toggle@1.1.0
npm notice === Tarball Contents ===
npm notice 2.4kB package.json
npm notice 1.1kB LICENSE
npm notice 4.0kB README.md
npm notice 5.0kB dist/doppler-feature-toggle.client.js
npm notice 1.9kB dist/doppler-feature-toggle.client.js.map
npm notice 4.6kB dist/doppler-feature-toggle.es5.js
npm notice 1.9kB dist/doppler-feature-toggle.es5.js.map
npm notice 5.3kB dist/doppler-feature-toggle.umd.js
npm notice 1.9kB dist/doppler-feature-toggle.umd.js.map
npm notice 393B  dist/lib/doppler-feature-toggle.js
npm notice 212B  dist/lib/doppler-feature-toggle.js.map
npm notice 124B  dist/lib/featureToggleClient.js
npm notice 133B  dist/lib/featureToggleClient.js.map
npm notice 123B  dist/lib/featureToggleRules.js
npm notice 131B  dist/lib/featureToggleRules.js.map
npm notice 3.8kB dist/lib/refFeatureToggleClient.js
npm notice 739B  dist/lib/refFeatureToggleClient.js.map
npm notice 68B   dist/types/doppler-feature-toggle.d.ts
npm notice 318B  dist/types/featureToggleClient.d.ts
npm notice 238B  dist/types/featureToggleRules.d.ts
npm notice 594B  dist/types/refFeatureToggleClient.d.ts
npm notice === Tarball Details ===
npm notice name:          doppler-feature-toggle
npm notice version:       1.1.0
npm notice package size:  7.5 kB
npm notice unpacked size: 34.9 kB
npm notice shasum:        57fba0d4f2a7b54ce2e7737f87ebf41f58f9bb01
npm notice integrity:     sha512-UnszL3HlpL/ma[...]herx6eOPPJudA==
npm notice total files:   21
npm notice
npm ERR! publish Failed PUT 403
npm ERR! code E403
npm ERR! You do not have permission to publish "doppler-feature-toggle". Are you logged in as the correct user? : doppler-feature-toggle

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-30T23_20_55_679Z-debug.log


    at makeError (/work/node_modules/execa/index.js:172:9)
    at Promise.all.then.arr (/work/node_modules/execa/index.js:277:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 1,
  stdout: '',
  stderr: 'npm notice \nnpm notice package: doppler-feature-toggle@1.1.0\nnpm notice === Tarball Contents === \nnpm notice 2.4kB package.json                             \nnpm notice 1.1kB LICENSE                                  \nnpm notice 4.0kB README.md                                \nnpm notice 5.0kB dist/doppler-feature-toggle.client.js    \nnpm notice 1.9kB dist/doppler-feature-toggle.client.js.map\nnpm notice 4.6kB dist/doppler-feature-toggle.es5.js       \nnpm notice 1.9kB dist/doppler-feature-toggle.es5.js.map   \nnpm notice 5.3kB dist/doppler-feature-toggle.umd.js       \nnpm notice 1.9kB dist/doppler-feature-toggle.umd.js.map   \nnpm notice 393B  dist/lib/doppler-feature-toggle.js       \nnpm notice 212B  dist/lib/doppler-feature-toggle.js.map   \nnpm notice 124B  dist/lib/featureToggleClient.js          \nnpm notice 133B  dist/lib/featureToggleClient.js.map      \nnpm notice 123B  dist/lib/featureToggleRules.js           \nnpm notice 131B  dist/lib/featureToggleRules.js.map       \nnpm notice 3.8kB dist/lib/refFeatureToggleClient.js       \nnpm notice 739B  dist/lib/refFeatureToggleClient.js.map   \nnpm notice 68B   dist/types/doppler-feature-toggle.d.ts   \nnpm notice 318B  dist/types/featureToggleClient.d.ts      \nnpm notice 238B  dist/types/featureToggleRules.d.ts       \nnpm notice 594B  dist/types/refFeatureToggleClient.d.ts   \nnpm notice === Tarball Details === \nnpm notice name:          doppler-feature-toggle                  \nnpm notice version:       1.1.0                                   \nnpm notice package size:  7.5 kB                                  \nnpm notice unpacked size: 34.9 kB                                 \nnpm notice shasum:        57fba0d4f2a7b54ce2e7737f87ebf41f58f9bb01\nnpm notice integrity:     sha512-UnszL3HlpL/ma[...]herx6eOPPJudA==\nnpm notice total files:   21                                      \nnpm notice \nnpm ERR! publish Failed PUT 403\nnpm ERR! code E403\nnpm ERR! You do not have permission to publish "doppler-feature-toggle". Are you logged in as the correct user? : doppler-feature-toggle\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /root/.npm/_logs/2018-08-30T23_20_55_679Z-debug.log\n',
  failed: true,
  signal: null,
  cmd: 'npm publish /work --registry https://registry.npmjs.org/',
  timedOut: false,
  killed: false,
  pluginName: '@semantic-release/npm' }
{ Error: Command failed: npm publish /work --registry https://registry.npmjs.org/
npm notice
npm notice package: doppler-feature-toggle@1.1.0
npm notice === Tarball Contents ===
npm notice 2.4kB package.json
npm notice 1.1kB LICENSE
npm notice 4.0kB README.md
npm notice 5.0kB dist/doppler-feature-toggle.client.js
npm notice 1.9kB dist/doppler-feature-toggle.client.js.map
npm notice 4.6kB dist/doppler-feature-toggle.es5.js
npm notice 1.9kB dist/doppler-feature-toggle.es5.js.map
npm notice 5.3kB dist/doppler-feature-toggle.umd.js
npm notice 1.9kB dist/doppler-feature-toggle.umd.js.map
npm notice 393B  dist/lib/doppler-feature-toggle.js
npm notice 212B  dist/lib/doppler-feature-toggle.js.map
npm notice 124B  dist/lib/featureToggleClient.js
npm notice 133B  dist/lib/featureToggleClient.js.map
npm notice 123B  dist/lib/featureToggleRules.js
npm notice 131B  dist/lib/featureToggleRules.js.map
npm notice 3.8kB dist/lib/refFeatureToggleClient.js
npm notice 739B  dist/lib/refFeatureToggleClient.js.map
npm notice 68B   dist/types/doppler-feature-toggle.d.ts
npm notice 318B  dist/types/featureToggleClient.d.ts
npm notice 238B  dist/types/featureToggleRules.d.ts
npm notice 594B  dist/types/refFeatureToggleClient.d.ts
npm notice === Tarball Details ===
npm notice name:          doppler-feature-toggle
npm notice version:       1.1.0
npm notice package size:  7.5 kB
npm notice unpacked size: 34.9 kB
npm notice shasum:        57fba0d4f2a7b54ce2e7737f87ebf41f58f9bb01
npm notice integrity:     sha512-UnszL3HlpL/ma[...]herx6eOPPJudA==
npm notice total files:   21
npm notice
npm ERR! publish Failed PUT 403
npm ERR! code E403
npm ERR! You do not have permission to publish "doppler-feature-toggle". Are you logged in as the correct user? : doppler-feature-toggle

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-30T23_20_55_679Z-debug.log


    at makeError (/work/node_modules/execa/index.js:172:9)
    at Promise.all.then.arr (/work/node_modules/execa/index.js:277:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 1,
  stdout: '',
  stderr: 'npm notice \nnpm notice package: doppler-feature-toggle@1.1.0\nnpm notice === Tarball Contents === \nnpm notice 2.4kB package.json                             \nnpm notice 1.1kB LICENSE                                  \nnpm notice 4.0kB README.md                                \nnpm notice 5.0kB dist/doppler-feature-toggle.client.js    \nnpm notice 1.9kB dist/doppler-feature-toggle.client.js.map\nnpm notice 4.6kB dist/doppler-feature-toggle.es5.js       \nnpm notice 1.9kB dist/doppler-feature-toggle.es5.js.map   \nnpm notice 5.3kB dist/doppler-feature-toggle.umd.js       \nnpm notice 1.9kB dist/doppler-feature-toggle.umd.js.map   \nnpm notice 393B  dist/lib/doppler-feature-toggle.js       \nnpm notice 212B  dist/lib/doppler-feature-toggle.js.map   \nnpm notice 124B  dist/lib/featureToggleClient.js          \nnpm notice 133B  dist/lib/featureToggleClient.js.map      \nnpm notice 123B  dist/lib/featureToggleRules.js           \nnpm notice 131B  dist/lib/featureToggleRules.js.map       \nnpm notice 3.8kB dist/lib/refFeatureToggleClient.js       \nnpm notice 739B  dist/lib/refFeatureToggleClient.js.map   \nnpm notice 68B   dist/types/doppler-feature-toggle.d.ts   \nnpm notice 318B  dist/types/featureToggleClient.d.ts      \nnpm notice 238B  dist/types/featureToggleRules.d.ts       \nnpm notice 594B  dist/types/refFeatureToggleClient.d.ts   \nnpm notice === Tarball Details === \nnpm notice name:          doppler-feature-toggle                  \nnpm notice version:       1.1.0                                   \nnpm notice package size:  7.5 kB                                  \nnpm notice unpacked size: 34.9 kB                                 \nnpm notice shasum:        57fba0d4f2a7b54ce2e7737f87ebf41f58f9bb01\nnpm notice integrity:     sha512-UnszL3HlpL/ma[...]herx6eOPPJudA==\nnpm notice total files:   21                                      \nnpm notice \nnpm ERR! publish Failed PUT 403\nnpm ERR! code E403\nnpm ERR! You do not have permission to publish "doppler-feature-toggle". Are you logged in as the correct user? : doppler-feature-toggle\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /root/.npm/_logs/2018-08-30T23_20_55_679Z-debug.log\n',
  failed: true,
  signal: null,
  cmd: 'npm publish /work --registry https://registry.npmjs.org/',
  timedOut: false,
  killed: false,
  pluginName: '@semantic-release/npm' }error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root@docker:/var/lib/jenkins/workspace/doppler-feature-toggle-js/releases#
```

Solution???

**Comment by andresmoschini** [comment]
There was an issue in how NPM had dealt with mi deprecated version, I sent an email to support and they have fixed it.
